export const CODE_INSIGHT_NOT_READY = 45;
export const CODE_INSIGHT_NOT_ENOUGH = 46;
export const CODE_INSIGHT_NOT_ERROR = 47;

export const INSIGHT_ERROR_CODES = [
  CODE_INSIGHT_NOT_READY,
  CODE_INSIGHT_NOT_ENOUGH,
  CODE_INSIGHT_NOT_ERROR,
];
